# Generated by Django 5.2 on 2025-05-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_candidates'),
        ('users', '0002_alter_user_role_candidateprofile_managerprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skills.skill'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
