# Generated by Django 5.2 on 2025-05-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.ManyToManyField(related_name='jobs', to='candidates.skill'),
        ),
    ]
